name: "CI Tests"

env:
  ImageOS: ubuntu22

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on:
      - runs-on
      - runner=2cpu-linux-x64
      - "run-id=${{ github.run_id }}"
    name: "[${{matrix.otp}}/${{matrix.elixir}}] CI Tests on Credo [OTP/Elixir]"
    strategy:
      matrix:
        otp: [20.3, 21.3, 22.2]
        elixir: [1.6.6, 1.7.2, 1.8.2, 1.9.4, 1.10.0]
    steps:
      - uses: actions/checkout@v2
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.0')"

      - uses: actions/setup-elixir@v1
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.0')"
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - run: mix deps.get
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.0')"

      - run: mix deps.compile
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.0')"

      - run: mix compile --warnings-as-errors
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.0')"

      - run: mix test
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.0')"

      - run: ./test/smoke_test.sh
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.0')"
