name: "Compatibility: Elixir"

env:
  ImageOS: ubuntu22

on:
  push:
    branches:
      - master

jobs:
  test_on_source:
    runs-on:
      - runs-on
      - runner=2cpu-linux-x64
      - "run-id=${{ github.run_id }}"
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    name: "[${{matrix.otp}}/${{matrix.elixir}}] Elixir ${{matrix.repo_branch}} source code analysed by Credo [OTP/Elixir]"
    strategy:
      matrix:
        otp: [24.2]
        elixir: [1.16]
        repo_url: ["https://github.com/elixir-lang/elixir.git"]
        repo_branch: ["v1.16", "master"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: mkdir -p tmp
      - run: git clone ${{matrix.repo_url}} tmp/${{matrix.repo_branch}} --depth=1 --branch ${{matrix.repo_branch}}
      - run: mix credo tmp/${{matrix.repo_branch}} --strict --mute-exit-status
