name: "Compatibility: Elixir"

env:
  ImageOS: ubuntu22

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test_on_source:
    runs-on:
      - runs-on
      - runner=2cpu-linux-x64
      - "run-id=${{ github.run_id }}"
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    name: "[${{matrix.otp}}/${{matrix.elixir}}] Elixir ${{matrix.repo_branch}} source code analysed by Credo [OTP/Elixir]"
    strategy:
      matrix:
        otp: [24.2.2]
        elixir: [1.12]
        repo_url: ["https://github.com/elixir-lang/elixir.git"]
        repo_branch: ["v1.12", "master"]
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Setup mise
        uses: step-security/mise-action@2796166110dee826668caddd4bffedae5116e7cd # v4.2.0

      - run: mix local.hex --force --if-missing
      - run: mix local.rebar --force --if-missing
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: mkdir -p tmp
      - run: git clone ${{matrix.repo_url}} tmp/${{matrix.repo_branch}} --depth=1 --branch ${{matrix.repo_branch}}
      - run: mix credo tmp/${{matrix.repo_branch}} --strict --mute-exit-status
